### ISSUE TITLE
клик по source  \ timer \ info \ thread

### ISSUE THREAD

**Issue by AlexeySpiridonov** [AlexeySpiridonov/PRFLR#15]
клик по значению любого поля   подставляет это значение в строку фильтра и делает поиск, другие значения сбрасываются

**Comment by andreyevsyukov** [comment]
Сделал, чтобы работали клики по каждому из item: source \ timer \ info \ thread
Так же есть клик по всей row - тогда в фильтр подставляется все значения, которые есть... возможно, это не требутся.

**Comment by AlexeySpiridonov** [comment]
немного неудобно.  надо чтобы клик  подставлял значение в нужный чанк строки,  а повторный клик менял обратно на звезду

**Comment by andreyevsyukov** [comment]
То есть при клике в "nodex.domain.com" фильтр вида "_/Action.messages/_/_" превратится в "nodex.domain.com/Action.messages/_/*" ?
